try {
    let a;
    console.log(a.length);
} catch (e) {
    // console.log(e);
    console.log("inside catch statement")
}
console.log("hi there");